version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: dockerworld-frontend
    command: npm run start
    ports:
    - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
    - ./frontend/src:/usr/src/app/src

  api:
    build: ./api
    container_name: dockerworld-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=http://localhost
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: dockerworld-auth
    command: npm run start
    restart: unless-stopped
    ports:
    - "3005:3005"
    environment:
      - PORT=3005
      - HOST=http://localhost
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: dockerworld-api-db
    volumes:
    - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: dockerworld-auth-db
    volumes:
    - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth: