version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: dockerworld-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - dockerworld-network


  api:
    build: ./api
    container_name: dockerworld-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=http://localhost
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3005/api
    depends_on:
      - api_db
    networks:
      - dockerworld-network

  auth:
    build: ./auth
    container_name: dockerworld-auth
    command: npm run start
    restart: unless-stopped
    ports:
    - "3005:3005"
    environment:
      - PORT=3005
      - HOST=http://localhost
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:8000/api
    depends_on:
      - auth_db
    networks:
      - dockerworld-network

  api_db:
    image: mongo:latest
    container_name: dockerworld-api-db
    volumes:
    - mongodb_api:/data/db
    networks:
      - dockerworld-network

  auth_db:
    image: mongo:latest
    container_name: dockerworld-auth-db
    volumes:
    - mongodb_auth:/data/db
    networks:
      - dockerworld-network

  nginx:
    image: nginx:stable-alpine
    container_name: dockerworld-nginx
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - dockerworld-network


volumes:
  mongodb_api:
  mongodb_auth:

networks:
  dockerworld-network:
    driver: bridge